-- Migration: init
-- Created: 2025-12-20

CREATE TABLE IF NOT EXISTS players (
    id CHAR(36) PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    hp INT NOT NULL DEFAULT 100,
    max_hp INT NOT NULL DEFAULT 100,
    attack INT NOT NULL DEFAULT 10,
    defense INT NOT NULL DEFAULT 5,
    exp INT NOT NULL DEFAULT 0,
    level INT NOT NULL DEFAULT 1,
    pos_x INT NOT NULL DEFAULT 5,
    pos_y INT NOT NULL DEFAULT 5,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_players_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
