// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/proto/game.proto

package gamev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Direction represents movement direction.
type Direction int32

const (
	Direction_DIRECTION_UNSPECIFIED Direction = 0
	Direction_DIRECTION_UP          Direction = 1
	Direction_DIRECTION_DOWN        Direction = 2
	Direction_DIRECTION_LEFT        Direction = 3
	Direction_DIRECTION_RIGHT       Direction = 4
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "DIRECTION_UNSPECIFIED",
		1: "DIRECTION_UP",
		2: "DIRECTION_DOWN",
		3: "DIRECTION_LEFT",
		4: "DIRECTION_RIGHT",
	}
	Direction_value = map[string]int32{
		"DIRECTION_UNSPECIFIED": 0,
		"DIRECTION_UP":          1,
		"DIRECTION_DOWN":        2,
		"DIRECTION_LEFT":        3,
		"DIRECTION_RIGHT":       4,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_game_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_api_proto_game_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{0}
}

// EventType represents the type of game event.
type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED     EventType = 0
	EventType_EVENT_TYPE_PLAYER_JOINED   EventType = 1
	EventType_EVENT_TYPE_PLAYER_LEFT     EventType = 2
	EventType_EVENT_TYPE_PLAYER_MOVED    EventType = 3
	EventType_EVENT_TYPE_PLAYER_DIED     EventType = 4
	EventType_EVENT_TYPE_PLAYER_LEVEL_UP EventType = 5
	EventType_EVENT_TYPE_COMBAT_STARTED  EventType = 10
	EventType_EVENT_TYPE_COMBAT_TURN     EventType = 11
	EventType_EVENT_TYPE_COMBAT_ENDED    EventType = 12
	EventType_EVENT_TYPE_MONSTER_MOVED   EventType = 20
	EventType_EVENT_TYPE_MONSTER_DIED    EventType = 21
	EventType_EVENT_TYPE_MONSTER_SPAWNED EventType = 22
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:  "EVENT_TYPE_UNSPECIFIED",
		1:  "EVENT_TYPE_PLAYER_JOINED",
		2:  "EVENT_TYPE_PLAYER_LEFT",
		3:  "EVENT_TYPE_PLAYER_MOVED",
		4:  "EVENT_TYPE_PLAYER_DIED",
		5:  "EVENT_TYPE_PLAYER_LEVEL_UP",
		10: "EVENT_TYPE_COMBAT_STARTED",
		11: "EVENT_TYPE_COMBAT_TURN",
		12: "EVENT_TYPE_COMBAT_ENDED",
		20: "EVENT_TYPE_MONSTER_MOVED",
		21: "EVENT_TYPE_MONSTER_DIED",
		22: "EVENT_TYPE_MONSTER_SPAWNED",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":     0,
		"EVENT_TYPE_PLAYER_JOINED":   1,
		"EVENT_TYPE_PLAYER_LEFT":     2,
		"EVENT_TYPE_PLAYER_MOVED":    3,
		"EVENT_TYPE_PLAYER_DIED":     4,
		"EVENT_TYPE_PLAYER_LEVEL_UP": 5,
		"EVENT_TYPE_COMBAT_STARTED":  10,
		"EVENT_TYPE_COMBAT_TURN":     11,
		"EVENT_TYPE_COMBAT_ENDED":    12,
		"EVENT_TYPE_MONSTER_MOVED":   20,
		"EVENT_TYPE_MONSTER_DIED":    21,
		"EVENT_TYPE_MONSTER_SPAWNED": 22,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_game_proto_enumTypes[1].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_api_proto_game_proto_enumTypes[1]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{1}
}

// CombatEndReason represents why combat ended.
type CombatEndReason int32

const (
	CombatEndReason_COMBAT_END_REASON_UNSPECIFIED CombatEndReason = 0
	CombatEndReason_COMBAT_END_REASON_RETREAT     CombatEndReason = 1
	CombatEndReason_COMBAT_END_REASON_DEATH       CombatEndReason = 2
	CombatEndReason_COMBAT_END_REASON_VICTORY     CombatEndReason = 3
)

// Enum value maps for CombatEndReason.
var (
	CombatEndReason_name = map[int32]string{
		0: "COMBAT_END_REASON_UNSPECIFIED",
		1: "COMBAT_END_REASON_RETREAT",
		2: "COMBAT_END_REASON_DEATH",
		3: "COMBAT_END_REASON_VICTORY",
	}
	CombatEndReason_value = map[string]int32{
		"COMBAT_END_REASON_UNSPECIFIED": 0,
		"COMBAT_END_REASON_RETREAT":     1,
		"COMBAT_END_REASON_DEATH":       2,
		"COMBAT_END_REASON_VICTORY":     3,
	}
)

func (x CombatEndReason) Enum() *CombatEndReason {
	p := new(CombatEndReason)
	*p = x
	return p
}

func (x CombatEndReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CombatEndReason) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_game_proto_enumTypes[2].Descriptor()
}

func (CombatEndReason) Type() protoreflect.EnumType {
	return &file_api_proto_game_proto_enumTypes[2]
}

func (x CombatEndReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CombatEndReason.Descriptor instead.
func (CombatEndReason) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{2}
}

// Position represents a coordinate on the map.
type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_api_proto_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// ConnectRequest is the request to connect to the game.
type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerName    string                 `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_api_proto_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

// ConnectResponse is the response after connecting.
type ConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Status        *PlayerStatus          `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_api_proto_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectResponse) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ConnectResponse) GetStatus() *PlayerStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// DisconnectRequest is the request to disconnect.
type DisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectRequest) Reset() {
	*x = DisconnectRequest{}
	mi := &file_api_proto_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRequest) ProtoMessage() {}

func (x *DisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRequest.ProtoReflect.Descriptor instead.
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{3}
}

func (x *DisconnectRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

// DisconnectResponse is the response after disconnecting.
type DisconnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectResponse) Reset() {
	*x = DisconnectResponse{}
	mi := &file_api_proto_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectResponse) ProtoMessage() {}

func (x *DisconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectResponse.ProtoReflect.Descriptor instead.
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{4}
}

func (x *DisconnectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// MoveRequest is the request to move.
type MoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Direction     Direction              `protobuf:"varint,2,opt,name=direction,proto3,enum=game.v1.Direction" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveRequest) Reset() {
	*x = MoveRequest{}
	mi := &file_api_proto_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRequest) ProtoMessage() {}

func (x *MoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRequest.ProtoReflect.Descriptor instead.
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{5}
}

func (x *MoveRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *MoveRequest) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNSPECIFIED
}

// MoveResponse is the response after moving.
type MoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewPosition   *Position              `protobuf:"bytes,2,opt,name=new_position,json=newPosition,proto3" json:"new_position,omitempty"`
	CombatStarted bool                   `protobuf:"varint,3,opt,name=combat_started,json=combatStarted,proto3" json:"combat_started,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveResponse) Reset() {
	*x = MoveResponse{}
	mi := &file_api_proto_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveResponse) ProtoMessage() {}

func (x *MoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveResponse.ProtoReflect.Descriptor instead.
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{6}
}

func (x *MoveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MoveResponse) GetNewPosition() *Position {
	if x != nil {
		return x.NewPosition
	}
	return nil
}

func (x *MoveResponse) GetCombatStarted() bool {
	if x != nil {
		return x.CombatStarted
	}
	return false
}

func (x *MoveResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// AttackRequest is the request to attack.
type AttackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttackRequest) Reset() {
	*x = AttackRequest{}
	mi := &file_api_proto_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackRequest) ProtoMessage() {}

func (x *AttackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackRequest.ProtoReflect.Descriptor instead.
func (*AttackRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{7}
}

func (x *AttackRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

// AttackResponse is the response after attacking.
type AttackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Result        *CombatResult          `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttackResponse) Reset() {
	*x = AttackResponse{}
	mi := &file_api_proto_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackResponse) ProtoMessage() {}

func (x *AttackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackResponse.ProtoReflect.Descriptor instead.
func (*AttackResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{8}
}

func (x *AttackResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AttackResponse) GetResult() *CombatResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *AttackResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// RetreatRequest is the request to retreat.
type RetreatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetreatRequest) Reset() {
	*x = RetreatRequest{}
	mi := &file_api_proto_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetreatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetreatRequest) ProtoMessage() {}

func (x *RetreatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetreatRequest.ProtoReflect.Descriptor instead.
func (*RetreatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{9}
}

func (x *RetreatRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

// RetreatResponse is the response after retreating.
type RetreatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewPosition   *Position              `protobuf:"bytes,2,opt,name=new_position,json=newPosition,proto3" json:"new_position,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetreatResponse) Reset() {
	*x = RetreatResponse{}
	mi := &file_api_proto_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetreatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetreatResponse) ProtoMessage() {}

func (x *RetreatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetreatResponse.ProtoReflect.Descriptor instead.
func (*RetreatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{10}
}

func (x *RetreatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RetreatResponse) GetNewPosition() *Position {
	if x != nil {
		return x.NewPosition
	}
	return nil
}

func (x *RetreatResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GetPlayerStatusRequest is the request to get player status.
type GetPlayerStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerStatusRequest) Reset() {
	*x = GetPlayerStatusRequest{}
	mi := &file_api_proto_game_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerStatusRequest) ProtoMessage() {}

func (x *GetPlayerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerStatusRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{11}
}

func (x *GetPlayerStatusRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

// GetPlayerStatusResponse is the response with player status.
type GetPlayerStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *PlayerStatus          `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerStatusResponse) Reset() {
	*x = GetPlayerStatusResponse{}
	mi := &file_api_proto_game_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerStatusResponse) ProtoMessage() {}

func (x *GetPlayerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerStatusResponse.ProtoReflect.Descriptor instead.
func (*GetPlayerStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{12}
}

func (x *GetPlayerStatusResponse) GetStatus() *PlayerStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// GetMapRequest is the request to get the map.
type GetMapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMapRequest) Reset() {
	*x = GetMapRequest{}
	mi := &file_api_proto_game_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMapRequest) ProtoMessage() {}

func (x *GetMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMapRequest.ProtoReflect.Descriptor instead.
func (*GetMapRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{13}
}

func (x *GetMapRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

// GetMapResponse is the response with the map state.
type GetMapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Map           *MapState              `protobuf:"bytes,1,opt,name=map,proto3" json:"map,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMapResponse) Reset() {
	*x = GetMapResponse{}
	mi := &file_api_proto_game_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMapResponse) ProtoMessage() {}

func (x *GetMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMapResponse.ProtoReflect.Descriptor instead.
func (*GetMapResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{14}
}

func (x *GetMapResponse) GetMap() *MapState {
	if x != nil {
		return x.Map
	}
	return nil
}

// SubscribeRequest is the request to subscribe to events.
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_api_proto_game_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{15}
}

func (x *SubscribeRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

// PlayerStatus represents a player's current status.
type PlayerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Hp            int32                  `protobuf:"varint,3,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp         int32                  `protobuf:"varint,4,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	Attack        int32                  `protobuf:"varint,5,opt,name=attack,proto3" json:"attack,omitempty"`
	Defense       int32                  `protobuf:"varint,6,opt,name=defense,proto3" json:"defense,omitempty"`
	Exp           int32                  `protobuf:"varint,7,opt,name=exp,proto3" json:"exp,omitempty"`
	Level         int32                  `protobuf:"varint,8,opt,name=level,proto3" json:"level,omitempty"`
	Position      *Position              `protobuf:"bytes,9,opt,name=position,proto3" json:"position,omitempty"`
	InCombat      bool                   `protobuf:"varint,10,opt,name=in_combat,json=inCombat,proto3" json:"in_combat,omitempty"`
	CombatTarget  *CombatTarget          `protobuf:"bytes,11,opt,name=combat_target,json=combatTarget,proto3" json:"combat_target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerStatus) Reset() {
	*x = PlayerStatus{}
	mi := &file_api_proto_game_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerStatus) ProtoMessage() {}

func (x *PlayerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerStatus.ProtoReflect.Descriptor instead.
func (*PlayerStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{16}
}

func (x *PlayerStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlayerStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerStatus) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *PlayerStatus) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *PlayerStatus) GetAttack() int32 {
	if x != nil {
		return x.Attack
	}
	return 0
}

func (x *PlayerStatus) GetDefense() int32 {
	if x != nil {
		return x.Defense
	}
	return 0
}

func (x *PlayerStatus) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *PlayerStatus) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PlayerStatus) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PlayerStatus) GetInCombat() bool {
	if x != nil {
		return x.InCombat
	}
	return false
}

func (x *PlayerStatus) GetCombatTarget() *CombatTarget {
	if x != nil {
		return x.CombatTarget
	}
	return nil
}

// CombatTarget represents the current combat target.
type CombatTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Hp            int32                  `protobuf:"varint,3,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp         int32                  `protobuf:"varint,4,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombatTarget) Reset() {
	*x = CombatTarget{}
	mi := &file_api_proto_game_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatTarget) ProtoMessage() {}

func (x *CombatTarget) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatTarget.ProtoReflect.Descriptor instead.
func (*CombatTarget) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{17}
}

func (x *CombatTarget) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CombatTarget) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CombatTarget) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *CombatTarget) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

// CombatResult represents the result of a combat action.
type CombatResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Turn          int32                  `protobuf:"varint,1,opt,name=turn,proto3" json:"turn,omitempty"`
	PlayerDamage  int32                  `protobuf:"varint,2,opt,name=player_damage,json=playerDamage,proto3" json:"player_damage,omitempty"`
	MonsterDamage int32                  `protobuf:"varint,3,opt,name=monster_damage,json=monsterDamage,proto3" json:"monster_damage,omitempty"`
	PlayerHp      int32                  `protobuf:"varint,4,opt,name=player_hp,json=playerHp,proto3" json:"player_hp,omitempty"`
	PlayerMaxHp   int32                  `protobuf:"varint,5,opt,name=player_max_hp,json=playerMaxHp,proto3" json:"player_max_hp,omitempty"`
	MonsterHp     int32                  `protobuf:"varint,6,opt,name=monster_hp,json=monsterHp,proto3" json:"monster_hp,omitempty"`
	MonsterMaxHp  int32                  `protobuf:"varint,7,opt,name=monster_max_hp,json=monsterMaxHp,proto3" json:"monster_max_hp,omitempty"`
	PlayerDied    bool                   `protobuf:"varint,8,opt,name=player_died,json=playerDied,proto3" json:"player_died,omitempty"`
	MonsterDied   bool                   `protobuf:"varint,9,opt,name=monster_died,json=monsterDied,proto3" json:"monster_died,omitempty"`
	ExpGained     int32                  `protobuf:"varint,10,opt,name=exp_gained,json=expGained,proto3" json:"exp_gained,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombatResult) Reset() {
	*x = CombatResult{}
	mi := &file_api_proto_game_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatResult) ProtoMessage() {}

func (x *CombatResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatResult.ProtoReflect.Descriptor instead.
func (*CombatResult) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{18}
}

func (x *CombatResult) GetTurn() int32 {
	if x != nil {
		return x.Turn
	}
	return 0
}

func (x *CombatResult) GetPlayerDamage() int32 {
	if x != nil {
		return x.PlayerDamage
	}
	return 0
}

func (x *CombatResult) GetMonsterDamage() int32 {
	if x != nil {
		return x.MonsterDamage
	}
	return 0
}

func (x *CombatResult) GetPlayerHp() int32 {
	if x != nil {
		return x.PlayerHp
	}
	return 0
}

func (x *CombatResult) GetPlayerMaxHp() int32 {
	if x != nil {
		return x.PlayerMaxHp
	}
	return 0
}

func (x *CombatResult) GetMonsterHp() int32 {
	if x != nil {
		return x.MonsterHp
	}
	return 0
}

func (x *CombatResult) GetMonsterMaxHp() int32 {
	if x != nil {
		return x.MonsterMaxHp
	}
	return 0
}

func (x *CombatResult) GetPlayerDied() bool {
	if x != nil {
		return x.PlayerDied
	}
	return false
}

func (x *CombatResult) GetMonsterDied() bool {
	if x != nil {
		return x.MonsterDied
	}
	return false
}

func (x *CombatResult) GetExpGained() int32 {
	if x != nil {
		return x.ExpGained
	}
	return 0
}

// MapState represents the current state of the map.
type MapState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*PlayerInfo          `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	Monster       *MonsterInfo           `protobuf:"bytes,2,opt,name=monster,proto3" json:"monster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapState) Reset() {
	*x = MapState{}
	mi := &file_api_proto_game_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapState) ProtoMessage() {}

func (x *MapState) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapState.ProtoReflect.Descriptor instead.
func (*MapState) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{19}
}

func (x *MapState) GetPlayers() []*PlayerInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *MapState) GetMonster() *MonsterInfo {
	if x != nil {
		return x.Monster
	}
	return nil
}

// PlayerInfo represents a player on the map.
type PlayerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Position      *Position              `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	InCombat      bool                   `protobuf:"varint,4,opt,name=in_combat,json=inCombat,proto3" json:"in_combat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	mi := &file_api_proto_game_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{20}
}

func (x *PlayerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlayerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerInfo) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PlayerInfo) GetInCombat() bool {
	if x != nil {
		return x.InCombat
	}
	return false
}

// MonsterInfo represents the monster on the map.
type MonsterInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Position      *Position              `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Hp            int32                  `protobuf:"varint,4,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp         int32                  `protobuf:"varint,5,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonsterInfo) Reset() {
	*x = MonsterInfo{}
	mi := &file_api_proto_game_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonsterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonsterInfo) ProtoMessage() {}

func (x *MonsterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonsterInfo.ProtoReflect.Descriptor instead.
func (*MonsterInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{21}
}

func (x *MonsterInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MonsterInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MonsterInfo) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *MonsterInfo) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *MonsterInfo) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

// GameEvent represents a game event sent to clients.
type GameEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Type      EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=game.v1.EventType" json:"type,omitempty"`
	Timestamp int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*GameEvent_PlayerJoined
	//	*GameEvent_PlayerLeft
	//	*GameEvent_PlayerMoved
	//	*GameEvent_PlayerDied
	//	*GameEvent_PlayerLevelUp
	//	*GameEvent_CombatStarted
	//	*GameEvent_CombatTurn
	//	*GameEvent_CombatEnded
	//	*GameEvent_MonsterMoved
	//	*GameEvent_MonsterDied
	//	*GameEvent_MonsterSpawned
	Payload       isGameEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameEvent) Reset() {
	*x = GameEvent{}
	mi := &file_api_proto_game_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEvent) ProtoMessage() {}

func (x *GameEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEvent.ProtoReflect.Descriptor instead.
func (*GameEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{22}
}

func (x *GameEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *GameEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GameEvent) GetPayload() isGameEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GameEvent) GetPlayerJoined() *PlayerJoinedEvent {
	if x != nil {
		if x, ok := x.Payload.(*GameEvent_PlayerJoined); ok {
			return x.PlayerJoined
		}
	}
	return nil
}

func (x *GameEvent) GetPlayerLeft() *PlayerLeftEvent {
	if x != nil {
		if x, ok := x.Payload.(*GameEvent_PlayerLeft); ok {
			return x.PlayerLeft
		}
	}
	return nil
}

func (x *GameEvent) GetPlayerMoved() *PlayerMovedEvent {
	if x != nil {
		if x, ok := x.Payload.(*GameEvent_PlayerMoved); ok {
			return x.PlayerMoved
		}
	}
	return nil
}

func (x *GameEvent) GetPlayerDied() *PlayerDiedEvent {
	if x != nil {
		if x, ok := x.Payload.(*GameEvent_PlayerDied); ok {
			return x.PlayerDied
		}
	}
	return nil
}

func (x *GameEvent) GetPlayerLevelUp() *PlayerLevelUpEvent {
	if x != nil {
		if x, ok := x.Payload.(*GameEvent_PlayerLevelUp); ok {
			return x.PlayerLevelUp
		}
	}
	return nil
}

func (x *GameEvent) GetCombatStarted() *CombatStartedEvent {
	if x != nil {
		if x, ok := x.Payload.(*GameEvent_CombatStarted); ok {
			return x.CombatStarted
		}
	}
	return nil
}

func (x *GameEvent) GetCombatTurn() *CombatTurnEvent {
	if x != nil {
		if x, ok := x.Payload.(*GameEvent_CombatTurn); ok {
			return x.CombatTurn
		}
	}
	return nil
}

func (x *GameEvent) GetCombatEnded() *CombatEndedEvent {
	if x != nil {
		if x, ok := x.Payload.(*GameEvent_CombatEnded); ok {
			return x.CombatEnded
		}
	}
	return nil
}

func (x *GameEvent) GetMonsterMoved() *MonsterMovedEvent {
	if x != nil {
		if x, ok := x.Payload.(*GameEvent_MonsterMoved); ok {
			return x.MonsterMoved
		}
	}
	return nil
}

func (x *GameEvent) GetMonsterDied() *MonsterDiedEvent {
	if x != nil {
		if x, ok := x.Payload.(*GameEvent_MonsterDied); ok {
			return x.MonsterDied
		}
	}
	return nil
}

func (x *GameEvent) GetMonsterSpawned() *MonsterSpawnedEvent {
	if x != nil {
		if x, ok := x.Payload.(*GameEvent_MonsterSpawned); ok {
			return x.MonsterSpawned
		}
	}
	return nil
}

type isGameEvent_Payload interface {
	isGameEvent_Payload()
}

type GameEvent_PlayerJoined struct {
	PlayerJoined *PlayerJoinedEvent `protobuf:"bytes,10,opt,name=player_joined,json=playerJoined,proto3,oneof"`
}

type GameEvent_PlayerLeft struct {
	PlayerLeft *PlayerLeftEvent `protobuf:"bytes,11,opt,name=player_left,json=playerLeft,proto3,oneof"`
}

type GameEvent_PlayerMoved struct {
	PlayerMoved *PlayerMovedEvent `protobuf:"bytes,12,opt,name=player_moved,json=playerMoved,proto3,oneof"`
}

type GameEvent_PlayerDied struct {
	PlayerDied *PlayerDiedEvent `protobuf:"bytes,13,opt,name=player_died,json=playerDied,proto3,oneof"`
}

type GameEvent_PlayerLevelUp struct {
	PlayerLevelUp *PlayerLevelUpEvent `protobuf:"bytes,14,opt,name=player_level_up,json=playerLevelUp,proto3,oneof"`
}

type GameEvent_CombatStarted struct {
	CombatStarted *CombatStartedEvent `protobuf:"bytes,20,opt,name=combat_started,json=combatStarted,proto3,oneof"`
}

type GameEvent_CombatTurn struct {
	CombatTurn *CombatTurnEvent `protobuf:"bytes,21,opt,name=combat_turn,json=combatTurn,proto3,oneof"`
}

type GameEvent_CombatEnded struct {
	CombatEnded *CombatEndedEvent `protobuf:"bytes,22,opt,name=combat_ended,json=combatEnded,proto3,oneof"`
}

type GameEvent_MonsterMoved struct {
	MonsterMoved *MonsterMovedEvent `protobuf:"bytes,30,opt,name=monster_moved,json=monsterMoved,proto3,oneof"`
}

type GameEvent_MonsterDied struct {
	MonsterDied *MonsterDiedEvent `protobuf:"bytes,31,opt,name=monster_died,json=monsterDied,proto3,oneof"`
}

type GameEvent_MonsterSpawned struct {
	MonsterSpawned *MonsterSpawnedEvent `protobuf:"bytes,32,opt,name=monster_spawned,json=monsterSpawned,proto3,oneof"`
}

func (*GameEvent_PlayerJoined) isGameEvent_Payload() {}

func (*GameEvent_PlayerLeft) isGameEvent_Payload() {}

func (*GameEvent_PlayerMoved) isGameEvent_Payload() {}

func (*GameEvent_PlayerDied) isGameEvent_Payload() {}

func (*GameEvent_PlayerLevelUp) isGameEvent_Payload() {}

func (*GameEvent_CombatStarted) isGameEvent_Payload() {}

func (*GameEvent_CombatTurn) isGameEvent_Payload() {}

func (*GameEvent_CombatEnded) isGameEvent_Payload() {}

func (*GameEvent_MonsterMoved) isGameEvent_Payload() {}

func (*GameEvent_MonsterDied) isGameEvent_Payload() {}

func (*GameEvent_MonsterSpawned) isGameEvent_Payload() {}

// PlayerJoinedEvent is emitted when a player joins.
type PlayerJoinedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	Position      *Position              `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerJoinedEvent) Reset() {
	*x = PlayerJoinedEvent{}
	mi := &file_api_proto_game_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerJoinedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerJoinedEvent) ProtoMessage() {}

func (x *PlayerJoinedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerJoinedEvent.ProtoReflect.Descriptor instead.
func (*PlayerJoinedEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{23}
}

func (x *PlayerJoinedEvent) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerJoinedEvent) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *PlayerJoinedEvent) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

// PlayerLeftEvent is emitted when a player leaves.
type PlayerLeftEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLeftEvent) Reset() {
	*x = PlayerLeftEvent{}
	mi := &file_api_proto_game_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLeftEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLeftEvent) ProtoMessage() {}

func (x *PlayerLeftEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLeftEvent.ProtoReflect.Descriptor instead.
func (*PlayerLeftEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{24}
}

func (x *PlayerLeftEvent) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

// PlayerMovedEvent is emitted when a player moves.
type PlayerMovedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	From          *Position              `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            *Position              `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerMovedEvent) Reset() {
	*x = PlayerMovedEvent{}
	mi := &file_api_proto_game_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerMovedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMovedEvent) ProtoMessage() {}

func (x *PlayerMovedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMovedEvent.ProtoReflect.Descriptor instead.
func (*PlayerMovedEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{25}
}

func (x *PlayerMovedEvent) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerMovedEvent) GetFrom() *Position {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *PlayerMovedEvent) GetTo() *Position {
	if x != nil {
		return x.To
	}
	return nil
}

// PlayerDiedEvent is emitted when a player dies.
type PlayerDiedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerDiedEvent) Reset() {
	*x = PlayerDiedEvent{}
	mi := &file_api_proto_game_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerDiedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerDiedEvent) ProtoMessage() {}

func (x *PlayerDiedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerDiedEvent.ProtoReflect.Descriptor instead.
func (*PlayerDiedEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{26}
}

func (x *PlayerDiedEvent) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

// PlayerLevelUpEvent is emitted when a player levels up.
type PlayerLevelUpEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	NewLevel      int32                  `protobuf:"varint,2,opt,name=new_level,json=newLevel,proto3" json:"new_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLevelUpEvent) Reset() {
	*x = PlayerLevelUpEvent{}
	mi := &file_api_proto_game_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLevelUpEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLevelUpEvent) ProtoMessage() {}

func (x *PlayerLevelUpEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLevelUpEvent.ProtoReflect.Descriptor instead.
func (*PlayerLevelUpEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{27}
}

func (x *PlayerLevelUpEvent) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerLevelUpEvent) GetNewLevel() int32 {
	if x != nil {
		return x.NewLevel
	}
	return 0
}

// CombatStartedEvent is emitted when combat starts.
type CombatStartedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MonsterId     string                 `protobuf:"bytes,2,opt,name=monster_id,json=monsterId,proto3" json:"monster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombatStartedEvent) Reset() {
	*x = CombatStartedEvent{}
	mi := &file_api_proto_game_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatStartedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatStartedEvent) ProtoMessage() {}

func (x *CombatStartedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatStartedEvent.ProtoReflect.Descriptor instead.
func (*CombatStartedEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{28}
}

func (x *CombatStartedEvent) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *CombatStartedEvent) GetMonsterId() string {
	if x != nil {
		return x.MonsterId
	}
	return ""
}

// CombatTurnEvent is emitted after a combat turn.
type CombatTurnEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MonsterId     string                 `protobuf:"bytes,2,opt,name=monster_id,json=monsterId,proto3" json:"monster_id,omitempty"`
	PlayerDamage  int32                  `protobuf:"varint,3,opt,name=player_damage,json=playerDamage,proto3" json:"player_damage,omitempty"`
	MonsterDamage int32                  `protobuf:"varint,4,opt,name=monster_damage,json=monsterDamage,proto3" json:"monster_damage,omitempty"`
	PlayerHp      int32                  `protobuf:"varint,5,opt,name=player_hp,json=playerHp,proto3" json:"player_hp,omitempty"`
	PlayerMaxHp   int32                  `protobuf:"varint,6,opt,name=player_max_hp,json=playerMaxHp,proto3" json:"player_max_hp,omitempty"`
	MonsterHp     int32                  `protobuf:"varint,7,opt,name=monster_hp,json=monsterHp,proto3" json:"monster_hp,omitempty"`
	MonsterMaxHp  int32                  `protobuf:"varint,8,opt,name=monster_max_hp,json=monsterMaxHp,proto3" json:"monster_max_hp,omitempty"`
	Turn          int32                  `protobuf:"varint,9,opt,name=turn,proto3" json:"turn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombatTurnEvent) Reset() {
	*x = CombatTurnEvent{}
	mi := &file_api_proto_game_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatTurnEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatTurnEvent) ProtoMessage() {}

func (x *CombatTurnEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatTurnEvent.ProtoReflect.Descriptor instead.
func (*CombatTurnEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{29}
}

func (x *CombatTurnEvent) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *CombatTurnEvent) GetMonsterId() string {
	if x != nil {
		return x.MonsterId
	}
	return ""
}

func (x *CombatTurnEvent) GetPlayerDamage() int32 {
	if x != nil {
		return x.PlayerDamage
	}
	return 0
}

func (x *CombatTurnEvent) GetMonsterDamage() int32 {
	if x != nil {
		return x.MonsterDamage
	}
	return 0
}

func (x *CombatTurnEvent) GetPlayerHp() int32 {
	if x != nil {
		return x.PlayerHp
	}
	return 0
}

func (x *CombatTurnEvent) GetPlayerMaxHp() int32 {
	if x != nil {
		return x.PlayerMaxHp
	}
	return 0
}

func (x *CombatTurnEvent) GetMonsterHp() int32 {
	if x != nil {
		return x.MonsterHp
	}
	return 0
}

func (x *CombatTurnEvent) GetMonsterMaxHp() int32 {
	if x != nil {
		return x.MonsterMaxHp
	}
	return 0
}

func (x *CombatTurnEvent) GetTurn() int32 {
	if x != nil {
		return x.Turn
	}
	return 0
}

// CombatEndedEvent is emitted when combat ends.
type CombatEndedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MonsterId     string                 `protobuf:"bytes,2,opt,name=monster_id,json=monsterId,proto3" json:"monster_id,omitempty"`
	Reason        CombatEndReason        `protobuf:"varint,3,opt,name=reason,proto3,enum=game.v1.CombatEndReason" json:"reason,omitempty"`
	ExpGained     int32                  `protobuf:"varint,4,opt,name=exp_gained,json=expGained,proto3" json:"exp_gained,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombatEndedEvent) Reset() {
	*x = CombatEndedEvent{}
	mi := &file_api_proto_game_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatEndedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatEndedEvent) ProtoMessage() {}

func (x *CombatEndedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatEndedEvent.ProtoReflect.Descriptor instead.
func (*CombatEndedEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{30}
}

func (x *CombatEndedEvent) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *CombatEndedEvent) GetMonsterId() string {
	if x != nil {
		return x.MonsterId
	}
	return ""
}

func (x *CombatEndedEvent) GetReason() CombatEndReason {
	if x != nil {
		return x.Reason
	}
	return CombatEndReason_COMBAT_END_REASON_UNSPECIFIED
}

func (x *CombatEndedEvent) GetExpGained() int32 {
	if x != nil {
		return x.ExpGained
	}
	return 0
}

// MonsterMovedEvent is emitted when the monster moves.
type MonsterMovedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MonsterId     string                 `protobuf:"bytes,1,opt,name=monster_id,json=monsterId,proto3" json:"monster_id,omitempty"`
	From          *Position              `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            *Position              `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonsterMovedEvent) Reset() {
	*x = MonsterMovedEvent{}
	mi := &file_api_proto_game_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonsterMovedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonsterMovedEvent) ProtoMessage() {}

func (x *MonsterMovedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonsterMovedEvent.ProtoReflect.Descriptor instead.
func (*MonsterMovedEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{31}
}

func (x *MonsterMovedEvent) GetMonsterId() string {
	if x != nil {
		return x.MonsterId
	}
	return ""
}

func (x *MonsterMovedEvent) GetFrom() *Position {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *MonsterMovedEvent) GetTo() *Position {
	if x != nil {
		return x.To
	}
	return nil
}

// MonsterDiedEvent is emitted when the monster dies.
type MonsterDiedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MonsterId     string                 `protobuf:"bytes,1,opt,name=monster_id,json=monsterId,proto3" json:"monster_id,omitempty"`
	KillerId      string                 `protobuf:"bytes,2,opt,name=killer_id,json=killerId,proto3" json:"killer_id,omitempty"`
	Contributors  []string               `protobuf:"bytes,3,rep,name=contributors,proto3" json:"contributors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonsterDiedEvent) Reset() {
	*x = MonsterDiedEvent{}
	mi := &file_api_proto_game_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonsterDiedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonsterDiedEvent) ProtoMessage() {}

func (x *MonsterDiedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonsterDiedEvent.ProtoReflect.Descriptor instead.
func (*MonsterDiedEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{32}
}

func (x *MonsterDiedEvent) GetMonsterId() string {
	if x != nil {
		return x.MonsterId
	}
	return ""
}

func (x *MonsterDiedEvent) GetKillerId() string {
	if x != nil {
		return x.KillerId
	}
	return ""
}

func (x *MonsterDiedEvent) GetContributors() []string {
	if x != nil {
		return x.Contributors
	}
	return nil
}

// MonsterSpawnedEvent is emitted when the monster spawns.
type MonsterSpawnedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MonsterId     string                 `protobuf:"bytes,1,opt,name=monster_id,json=monsterId,proto3" json:"monster_id,omitempty"`
	Position      *Position              `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonsterSpawnedEvent) Reset() {
	*x = MonsterSpawnedEvent{}
	mi := &file_api_proto_game_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonsterSpawnedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonsterSpawnedEvent) ProtoMessage() {}

func (x *MonsterSpawnedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonsterSpawnedEvent.ProtoReflect.Descriptor instead.
func (*MonsterSpawnedEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{33}
}

func (x *MonsterSpawnedEvent) GetMonsterId() string {
	if x != nil {
		return x.MonsterId
	}
	return ""
}

func (x *MonsterSpawnedEvent) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

var File_api_proto_game_proto protoreflect.FileDescriptor

const file_api_proto_game_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/game.proto\x12\agame.v1\"&\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"1\n" +
	"\x0eConnectRequest\x12\x1f\n" +
	"\vplayer_name\x18\x01 \x01(\tR\n" +
	"playerName\"]\n" +
	"\x0fConnectResponse\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12-\n" +
	"\x06status\x18\x02 \x01(\v2\x15.game.v1.PlayerStatusR\x06status\"0\n" +
	"\x11DisconnectRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\".\n" +
	"\x12DisconnectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\\\n" +
	"\vMoveRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x120\n" +
	"\tdirection\x18\x02 \x01(\x0e2\x12.game.v1.DirectionR\tdirection\"\x9b\x01\n" +
	"\fMoveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x124\n" +
	"\fnew_position\x18\x02 \x01(\v2\x11.game.v1.PositionR\vnewPosition\x12%\n" +
	"\x0ecombat_started\x18\x03 \x01(\bR\rcombatStarted\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\",\n" +
	"\rAttackRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"o\n" +
	"\x0eAttackResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12-\n" +
	"\x06result\x18\x02 \x01(\v2\x15.game.v1.CombatResultR\x06result\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"-\n" +
	"\x0eRetreatRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"w\n" +
	"\x0fRetreatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x124\n" +
	"\fnew_position\x18\x02 \x01(\v2\x11.game.v1.PositionR\vnewPosition\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"5\n" +
	"\x16GetPlayerStatusRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"H\n" +
	"\x17GetPlayerStatusResponse\x12-\n" +
	"\x06status\x18\x01 \x01(\v2\x15.game.v1.PlayerStatusR\x06status\",\n" +
	"\rGetMapRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"5\n" +
	"\x0eGetMapResponse\x12#\n" +
	"\x03map\x18\x01 \x01(\v2\x11.game.v1.MapStateR\x03map\"/\n" +
	"\x10SubscribeRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"\xbb\x02\n" +
	"\fPlayerStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x0e\n" +
	"\x02hp\x18\x03 \x01(\x05R\x02hp\x12\x15\n" +
	"\x06max_hp\x18\x04 \x01(\x05R\x05maxHp\x12\x16\n" +
	"\x06attack\x18\x05 \x01(\x05R\x06attack\x12\x18\n" +
	"\adefense\x18\x06 \x01(\x05R\adefense\x12\x10\n" +
	"\x03exp\x18\a \x01(\x05R\x03exp\x12\x14\n" +
	"\x05level\x18\b \x01(\x05R\x05level\x12-\n" +
	"\bposition\x18\t \x01(\v2\x11.game.v1.PositionR\bposition\x12\x1b\n" +
	"\tin_combat\x18\n" +
	" \x01(\bR\binCombat\x12:\n" +
	"\rcombat_target\x18\v \x01(\v2\x15.game.v1.CombatTargetR\fcombatTarget\"Y\n" +
	"\fCombatTarget\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x0e\n" +
	"\x02hp\x18\x03 \x01(\x05R\x02hp\x12\x15\n" +
	"\x06max_hp\x18\x04 \x01(\x05R\x05maxHp\"\xd7\x02\n" +
	"\fCombatResult\x12\x12\n" +
	"\x04turn\x18\x01 \x01(\x05R\x04turn\x12#\n" +
	"\rplayer_damage\x18\x02 \x01(\x05R\fplayerDamage\x12%\n" +
	"\x0emonster_damage\x18\x03 \x01(\x05R\rmonsterDamage\x12\x1b\n" +
	"\tplayer_hp\x18\x04 \x01(\x05R\bplayerHp\x12\"\n" +
	"\rplayer_max_hp\x18\x05 \x01(\x05R\vplayerMaxHp\x12\x1d\n" +
	"\n" +
	"monster_hp\x18\x06 \x01(\x05R\tmonsterHp\x12$\n" +
	"\x0emonster_max_hp\x18\a \x01(\x05R\fmonsterMaxHp\x12\x1f\n" +
	"\vplayer_died\x18\b \x01(\bR\n" +
	"playerDied\x12!\n" +
	"\fmonster_died\x18\t \x01(\bR\vmonsterDied\x12\x1d\n" +
	"\n" +
	"exp_gained\x18\n" +
	" \x01(\x05R\texpGained\"i\n" +
	"\bMapState\x12-\n" +
	"\aplayers\x18\x01 \x03(\v2\x13.game.v1.PlayerInfoR\aplayers\x12.\n" +
	"\amonster\x18\x02 \x01(\v2\x14.game.v1.MonsterInfoR\amonster\"|\n" +
	"\n" +
	"PlayerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12-\n" +
	"\bposition\x18\x03 \x01(\v2\x11.game.v1.PositionR\bposition\x12\x1b\n" +
	"\tin_combat\x18\x04 \x01(\bR\binCombat\"\x87\x01\n" +
	"\vMonsterInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12-\n" +
	"\bposition\x18\x03 \x01(\v2\x11.game.v1.PositionR\bposition\x12\x0e\n" +
	"\x02hp\x18\x04 \x01(\x05R\x02hp\x12\x15\n" +
	"\x06max_hp\x18\x05 \x01(\x05R\x05maxHp\"\xaf\x06\n" +
	"\tGameEvent\x12&\n" +
	"\x04type\x18\x01 \x01(\x0e2\x12.game.v1.EventTypeR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12A\n" +
	"\rplayer_joined\x18\n" +
	" \x01(\v2\x1a.game.v1.PlayerJoinedEventH\x00R\fplayerJoined\x12;\n" +
	"\vplayer_left\x18\v \x01(\v2\x18.game.v1.PlayerLeftEventH\x00R\n" +
	"playerLeft\x12>\n" +
	"\fplayer_moved\x18\f \x01(\v2\x19.game.v1.PlayerMovedEventH\x00R\vplayerMoved\x12;\n" +
	"\vplayer_died\x18\r \x01(\v2\x18.game.v1.PlayerDiedEventH\x00R\n" +
	"playerDied\x12E\n" +
	"\x0fplayer_level_up\x18\x0e \x01(\v2\x1b.game.v1.PlayerLevelUpEventH\x00R\rplayerLevelUp\x12D\n" +
	"\x0ecombat_started\x18\x14 \x01(\v2\x1b.game.v1.CombatStartedEventH\x00R\rcombatStarted\x12;\n" +
	"\vcombat_turn\x18\x15 \x01(\v2\x18.game.v1.CombatTurnEventH\x00R\n" +
	"combatTurn\x12>\n" +
	"\fcombat_ended\x18\x16 \x01(\v2\x19.game.v1.CombatEndedEventH\x00R\vcombatEnded\x12A\n" +
	"\rmonster_moved\x18\x1e \x01(\v2\x1a.game.v1.MonsterMovedEventH\x00R\fmonsterMoved\x12>\n" +
	"\fmonster_died\x18\x1f \x01(\v2\x19.game.v1.MonsterDiedEventH\x00R\vmonsterDied\x12G\n" +
	"\x0fmonster_spawned\x18  \x01(\v2\x1c.game.v1.MonsterSpawnedEventH\x00R\x0emonsterSpawnedB\t\n" +
	"\apayload\"\x80\x01\n" +
	"\x11PlayerJoinedEvent\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\x12-\n" +
	"\bposition\x18\x03 \x01(\v2\x11.game.v1.PositionR\bposition\".\n" +
	"\x0fPlayerLeftEvent\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"y\n" +
	"\x10PlayerMovedEvent\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12%\n" +
	"\x04from\x18\x02 \x01(\v2\x11.game.v1.PositionR\x04from\x12!\n" +
	"\x02to\x18\x03 \x01(\v2\x11.game.v1.PositionR\x02to\".\n" +
	"\x0fPlayerDiedEvent\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"N\n" +
	"\x12PlayerLevelUpEvent\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1b\n" +
	"\tnew_level\x18\x02 \x01(\x05R\bnewLevel\"P\n" +
	"\x12CombatStartedEvent\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1d\n" +
	"\n" +
	"monster_id\x18\x02 \x01(\tR\tmonsterId\"\xb3\x02\n" +
	"\x0fCombatTurnEvent\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1d\n" +
	"\n" +
	"monster_id\x18\x02 \x01(\tR\tmonsterId\x12#\n" +
	"\rplayer_damage\x18\x03 \x01(\x05R\fplayerDamage\x12%\n" +
	"\x0emonster_damage\x18\x04 \x01(\x05R\rmonsterDamage\x12\x1b\n" +
	"\tplayer_hp\x18\x05 \x01(\x05R\bplayerHp\x12\"\n" +
	"\rplayer_max_hp\x18\x06 \x01(\x05R\vplayerMaxHp\x12\x1d\n" +
	"\n" +
	"monster_hp\x18\a \x01(\x05R\tmonsterHp\x12$\n" +
	"\x0emonster_max_hp\x18\b \x01(\x05R\fmonsterMaxHp\x12\x12\n" +
	"\x04turn\x18\t \x01(\x05R\x04turn\"\x9f\x01\n" +
	"\x10CombatEndedEvent\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1d\n" +
	"\n" +
	"monster_id\x18\x02 \x01(\tR\tmonsterId\x120\n" +
	"\x06reason\x18\x03 \x01(\x0e2\x18.game.v1.CombatEndReasonR\x06reason\x12\x1d\n" +
	"\n" +
	"exp_gained\x18\x04 \x01(\x05R\texpGained\"|\n" +
	"\x11MonsterMovedEvent\x12\x1d\n" +
	"\n" +
	"monster_id\x18\x01 \x01(\tR\tmonsterId\x12%\n" +
	"\x04from\x18\x02 \x01(\v2\x11.game.v1.PositionR\x04from\x12!\n" +
	"\x02to\x18\x03 \x01(\v2\x11.game.v1.PositionR\x02to\"r\n" +
	"\x10MonsterDiedEvent\x12\x1d\n" +
	"\n" +
	"monster_id\x18\x01 \x01(\tR\tmonsterId\x12\x1b\n" +
	"\tkiller_id\x18\x02 \x01(\tR\bkillerId\x12\"\n" +
	"\fcontributors\x18\x03 \x03(\tR\fcontributors\"c\n" +
	"\x13MonsterSpawnedEvent\x12\x1d\n" +
	"\n" +
	"monster_id\x18\x01 \x01(\tR\tmonsterId\x12-\n" +
	"\bposition\x18\x02 \x01(\v2\x11.game.v1.PositionR\bposition*u\n" +
	"\tDirection\x12\x19\n" +
	"\x15DIRECTION_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fDIRECTION_UP\x10\x01\x12\x12\n" +
	"\x0eDIRECTION_DOWN\x10\x02\x12\x12\n" +
	"\x0eDIRECTION_LEFT\x10\x03\x12\x13\n" +
	"\x0fDIRECTION_RIGHT\x10\x04*\xed\x02\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18EVENT_TYPE_PLAYER_JOINED\x10\x01\x12\x1a\n" +
	"\x16EVENT_TYPE_PLAYER_LEFT\x10\x02\x12\x1b\n" +
	"\x17EVENT_TYPE_PLAYER_MOVED\x10\x03\x12\x1a\n" +
	"\x16EVENT_TYPE_PLAYER_DIED\x10\x04\x12\x1e\n" +
	"\x1aEVENT_TYPE_PLAYER_LEVEL_UP\x10\x05\x12\x1d\n" +
	"\x19EVENT_TYPE_COMBAT_STARTED\x10\n" +
	"\x12\x1a\n" +
	"\x16EVENT_TYPE_COMBAT_TURN\x10\v\x12\x1b\n" +
	"\x17EVENT_TYPE_COMBAT_ENDED\x10\f\x12\x1c\n" +
	"\x18EVENT_TYPE_MONSTER_MOVED\x10\x14\x12\x1b\n" +
	"\x17EVENT_TYPE_MONSTER_DIED\x10\x15\x12\x1e\n" +
	"\x1aEVENT_TYPE_MONSTER_SPAWNED\x10\x16*\x8f\x01\n" +
	"\x0fCombatEndReason\x12!\n" +
	"\x1dCOMBAT_END_REASON_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19COMBAT_END_REASON_RETREAT\x10\x01\x12\x1b\n" +
	"\x17COMBAT_END_REASON_DEATH\x10\x02\x12\x1d\n" +
	"\x19COMBAT_END_REASON_VICTORY\x10\x032\x8f\x04\n" +
	"\vGameService\x12<\n" +
	"\aConnect\x12\x17.game.v1.ConnectRequest\x1a\x18.game.v1.ConnectResponse\x12E\n" +
	"\n" +
	"Disconnect\x12\x1a.game.v1.DisconnectRequest\x1a\x1b.game.v1.DisconnectResponse\x123\n" +
	"\x04Move\x12\x14.game.v1.MoveRequest\x1a\x15.game.v1.MoveResponse\x129\n" +
	"\x06Attack\x12\x16.game.v1.AttackRequest\x1a\x17.game.v1.AttackResponse\x12<\n" +
	"\aRetreat\x12\x17.game.v1.RetreatRequest\x1a\x18.game.v1.RetreatResponse\x12T\n" +
	"\x0fGetPlayerStatus\x12\x1f.game.v1.GetPlayerStatusRequest\x1a .game.v1.GetPlayerStatusResponse\x129\n" +
	"\x06GetMap\x12\x16.game.v1.GetMapRequest\x1a\x17.game.v1.GetMapResponse\x12<\n" +
	"\tSubscribe\x12\x19.game.v1.SubscribeRequest\x1a\x12.game.v1.GameEvent0\x01B#Z!mini-mud/api/proto/game/v1;gamev1b\x06proto3"

var (
	file_api_proto_game_proto_rawDescOnce sync.Once
	file_api_proto_game_proto_rawDescData []byte
)

func file_api_proto_game_proto_rawDescGZIP() []byte {
	file_api_proto_game_proto_rawDescOnce.Do(func() {
		file_api_proto_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_game_proto_rawDesc), len(file_api_proto_game_proto_rawDesc)))
	})
	return file_api_proto_game_proto_rawDescData
}

var file_api_proto_game_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_proto_game_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_api_proto_game_proto_goTypes = []any{
	(Direction)(0),                  // 0: game.v1.Direction
	(EventType)(0),                  // 1: game.v1.EventType
	(CombatEndReason)(0),            // 2: game.v1.CombatEndReason
	(*Position)(nil),                // 3: game.v1.Position
	(*ConnectRequest)(nil),          // 4: game.v1.ConnectRequest
	(*ConnectResponse)(nil),         // 5: game.v1.ConnectResponse
	(*DisconnectRequest)(nil),       // 6: game.v1.DisconnectRequest
	(*DisconnectResponse)(nil),      // 7: game.v1.DisconnectResponse
	(*MoveRequest)(nil),             // 8: game.v1.MoveRequest
	(*MoveResponse)(nil),            // 9: game.v1.MoveResponse
	(*AttackRequest)(nil),           // 10: game.v1.AttackRequest
	(*AttackResponse)(nil),          // 11: game.v1.AttackResponse
	(*RetreatRequest)(nil),          // 12: game.v1.RetreatRequest
	(*RetreatResponse)(nil),         // 13: game.v1.RetreatResponse
	(*GetPlayerStatusRequest)(nil),  // 14: game.v1.GetPlayerStatusRequest
	(*GetPlayerStatusResponse)(nil), // 15: game.v1.GetPlayerStatusResponse
	(*GetMapRequest)(nil),           // 16: game.v1.GetMapRequest
	(*GetMapResponse)(nil),          // 17: game.v1.GetMapResponse
	(*SubscribeRequest)(nil),        // 18: game.v1.SubscribeRequest
	(*PlayerStatus)(nil),            // 19: game.v1.PlayerStatus
	(*CombatTarget)(nil),            // 20: game.v1.CombatTarget
	(*CombatResult)(nil),            // 21: game.v1.CombatResult
	(*MapState)(nil),                // 22: game.v1.MapState
	(*PlayerInfo)(nil),              // 23: game.v1.PlayerInfo
	(*MonsterInfo)(nil),             // 24: game.v1.MonsterInfo
	(*GameEvent)(nil),               // 25: game.v1.GameEvent
	(*PlayerJoinedEvent)(nil),       // 26: game.v1.PlayerJoinedEvent
	(*PlayerLeftEvent)(nil),         // 27: game.v1.PlayerLeftEvent
	(*PlayerMovedEvent)(nil),        // 28: game.v1.PlayerMovedEvent
	(*PlayerDiedEvent)(nil),         // 29: game.v1.PlayerDiedEvent
	(*PlayerLevelUpEvent)(nil),      // 30: game.v1.PlayerLevelUpEvent
	(*CombatStartedEvent)(nil),      // 31: game.v1.CombatStartedEvent
	(*CombatTurnEvent)(nil),         // 32: game.v1.CombatTurnEvent
	(*CombatEndedEvent)(nil),        // 33: game.v1.CombatEndedEvent
	(*MonsterMovedEvent)(nil),       // 34: game.v1.MonsterMovedEvent
	(*MonsterDiedEvent)(nil),        // 35: game.v1.MonsterDiedEvent
	(*MonsterSpawnedEvent)(nil),     // 36: game.v1.MonsterSpawnedEvent
}
var file_api_proto_game_proto_depIdxs = []int32{
	19, // 0: game.v1.ConnectResponse.status:type_name -> game.v1.PlayerStatus
	0,  // 1: game.v1.MoveRequest.direction:type_name -> game.v1.Direction
	3,  // 2: game.v1.MoveResponse.new_position:type_name -> game.v1.Position
	21, // 3: game.v1.AttackResponse.result:type_name -> game.v1.CombatResult
	3,  // 4: game.v1.RetreatResponse.new_position:type_name -> game.v1.Position
	19, // 5: game.v1.GetPlayerStatusResponse.status:type_name -> game.v1.PlayerStatus
	22, // 6: game.v1.GetMapResponse.map:type_name -> game.v1.MapState
	3,  // 7: game.v1.PlayerStatus.position:type_name -> game.v1.Position
	20, // 8: game.v1.PlayerStatus.combat_target:type_name -> game.v1.CombatTarget
	23, // 9: game.v1.MapState.players:type_name -> game.v1.PlayerInfo
	24, // 10: game.v1.MapState.monster:type_name -> game.v1.MonsterInfo
	3,  // 11: game.v1.PlayerInfo.position:type_name -> game.v1.Position
	3,  // 12: game.v1.MonsterInfo.position:type_name -> game.v1.Position
	1,  // 13: game.v1.GameEvent.type:type_name -> game.v1.EventType
	26, // 14: game.v1.GameEvent.player_joined:type_name -> game.v1.PlayerJoinedEvent
	27, // 15: game.v1.GameEvent.player_left:type_name -> game.v1.PlayerLeftEvent
	28, // 16: game.v1.GameEvent.player_moved:type_name -> game.v1.PlayerMovedEvent
	29, // 17: game.v1.GameEvent.player_died:type_name -> game.v1.PlayerDiedEvent
	30, // 18: game.v1.GameEvent.player_level_up:type_name -> game.v1.PlayerLevelUpEvent
	31, // 19: game.v1.GameEvent.combat_started:type_name -> game.v1.CombatStartedEvent
	32, // 20: game.v1.GameEvent.combat_turn:type_name -> game.v1.CombatTurnEvent
	33, // 21: game.v1.GameEvent.combat_ended:type_name -> game.v1.CombatEndedEvent
	34, // 22: game.v1.GameEvent.monster_moved:type_name -> game.v1.MonsterMovedEvent
	35, // 23: game.v1.GameEvent.monster_died:type_name -> game.v1.MonsterDiedEvent
	36, // 24: game.v1.GameEvent.monster_spawned:type_name -> game.v1.MonsterSpawnedEvent
	3,  // 25: game.v1.PlayerJoinedEvent.position:type_name -> game.v1.Position
	3,  // 26: game.v1.PlayerMovedEvent.from:type_name -> game.v1.Position
	3,  // 27: game.v1.PlayerMovedEvent.to:type_name -> game.v1.Position
	2,  // 28: game.v1.CombatEndedEvent.reason:type_name -> game.v1.CombatEndReason
	3,  // 29: game.v1.MonsterMovedEvent.from:type_name -> game.v1.Position
	3,  // 30: game.v1.MonsterMovedEvent.to:type_name -> game.v1.Position
	3,  // 31: game.v1.MonsterSpawnedEvent.position:type_name -> game.v1.Position
	4,  // 32: game.v1.GameService.Connect:input_type -> game.v1.ConnectRequest
	6,  // 33: game.v1.GameService.Disconnect:input_type -> game.v1.DisconnectRequest
	8,  // 34: game.v1.GameService.Move:input_type -> game.v1.MoveRequest
	10, // 35: game.v1.GameService.Attack:input_type -> game.v1.AttackRequest
	12, // 36: game.v1.GameService.Retreat:input_type -> game.v1.RetreatRequest
	14, // 37: game.v1.GameService.GetPlayerStatus:input_type -> game.v1.GetPlayerStatusRequest
	16, // 38: game.v1.GameService.GetMap:input_type -> game.v1.GetMapRequest
	18, // 39: game.v1.GameService.Subscribe:input_type -> game.v1.SubscribeRequest
	5,  // 40: game.v1.GameService.Connect:output_type -> game.v1.ConnectResponse
	7,  // 41: game.v1.GameService.Disconnect:output_type -> game.v1.DisconnectResponse
	9,  // 42: game.v1.GameService.Move:output_type -> game.v1.MoveResponse
	11, // 43: game.v1.GameService.Attack:output_type -> game.v1.AttackResponse
	13, // 44: game.v1.GameService.Retreat:output_type -> game.v1.RetreatResponse
	15, // 45: game.v1.GameService.GetPlayerStatus:output_type -> game.v1.GetPlayerStatusResponse
	17, // 46: game.v1.GameService.GetMap:output_type -> game.v1.GetMapResponse
	25, // 47: game.v1.GameService.Subscribe:output_type -> game.v1.GameEvent
	40, // [40:48] is the sub-list for method output_type
	32, // [32:40] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_api_proto_game_proto_init() }
func file_api_proto_game_proto_init() {
	if File_api_proto_game_proto != nil {
		return
	}
	file_api_proto_game_proto_msgTypes[22].OneofWrappers = []any{
		(*GameEvent_PlayerJoined)(nil),
		(*GameEvent_PlayerLeft)(nil),
		(*GameEvent_PlayerMoved)(nil),
		(*GameEvent_PlayerDied)(nil),
		(*GameEvent_PlayerLevelUp)(nil),
		(*GameEvent_CombatStarted)(nil),
		(*GameEvent_CombatTurn)(nil),
		(*GameEvent_CombatEnded)(nil),
		(*GameEvent_MonsterMoved)(nil),
		(*GameEvent_MonsterDied)(nil),
		(*GameEvent_MonsterSpawned)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_game_proto_rawDesc), len(file_api_proto_game_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_game_proto_goTypes,
		DependencyIndexes: file_api_proto_game_proto_depIdxs,
		EnumInfos:         file_api_proto_game_proto_enumTypes,
		MessageInfos:      file_api_proto_game_proto_msgTypes,
	}.Build()
	File_api_proto_game_proto = out.File
	file_api_proto_game_proto_goTypes = nil
	file_api_proto_game_proto_depIdxs = nil
}
